// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQ71dQe03YQqiZAxOepXS7DaYJzSMsfM',
    appId: '1:50042525596:web:27588f08969d22410f5a59',
    messagingSenderId: '50042525596',
    projectId: 'splitdine',
    authDomain: 'splitdine.firebaseapp.com',
    storageBucket: 'splitdine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQ71dQe03YQqiZAxOepXS7DaYJzSMsfM',
    appId: '1:50042525596:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '50042525596',
    projectId: 'splitdine',
    storageBucket: 'splitdine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQ71dQe03YQqiZAxOepXS7DaYJzSMsfM',
    appId: '1:50042525596:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '50042525596',
    projectId: 'splitdine',
    storageBucket: 'splitdine.firebasestorage.app',
    iosBundleId: 'com.noodev8.splitdine2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQ71dQe03YQqiZAxOepXS7DaYJzSMsfM',
    appId: '1:50042525596:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '50042525596',
    projectId: 'splitdine',
    storageBucket: 'splitdine.firebasestorage.app',
    iosBundleId: 'com.noodev8.splitdine2',
  );
}
